server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: cambio_service
    user: root
    password: root
springdoc:
 api-docs:
  path: /cambio-service/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
 swagger-ui:
  enabled: true
  path: /swagger-ui.html
management:
  # endpoints:
  #   web:
  #     exposure:
  #       include: '*'
  tracing:
    sampling:
      probability: 1.0
  #   propagation:
  #     type: w3c
  #   baggage:
  #     enabled: true
  #   enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411